------------------------------------------------------------------------------
-- Challenge
------------------------------------------------------------------------------
/*
--- Day 4: Ceres Search ---
"Looks like the Chief's not here. Next!" One of The Historians pulls out a device and pushes the only button on it. After a brief flash, you recognize the interior of the Ceres monitoring station!

As the search for the Chief continues, a small Elf who lives on the station tugs on your shirt; she'd like to know if you could help her with her word search (your puzzle input). She only has to find one word: XMAS.

This word search allows words to be horizontal, vertical, diagonal, written backwards, or even overlapping other words. It's a little unusual, though, as you don't merely need to find one instance of XMAS - you need to find all of them. Here are a few ways XMAS might appear, where irrelevant characters have been replaced with .:


..X...
.SAMX.
.A..A.
XMAS.S
.X....
The actual word search will be full of letters instead. For example:

MMMSXXMASM
MSAMXMSMSA
AMXSXMAAMM
MSAMASMSMX
XMASAMXAMM
XXAMMXXAMA
SMSMSASXSS
SAXAMASAAA
MAMMMXMMMM
MXMXAXMASX
In this word search, XMAS occurs a total of 18 times; here's the same word search again, but where letters not involved in any XMAS have been replaced with .:

....XXMAS.
.SAMXMS...
...S..A...
..A.A.MS.X
XMASAMX.MM
X.....XA.A
S.S.S.S.SS
.A.A.A.A.A
..M.M.M.MM
.X.X.XMASX
Take a look at the little Elf's word search. How many times does XMAS appear?
*/
------------------------------------------------------------------------------

------------------------------------------------------------------------------
/*
--- Part Two ---
The Elf looks quizzically at you. Did you misunderstand the assignment?

Looking for the instructions, you flip over the word search to find that this isn't actually an XMAS puzzle; it's an X-MAS puzzle in which you're supposed to find two MAS in the shape of an X. One way to achieve that is like this:

M.S
.A.
M.S
Irrelevant characters have again been replaced with . in the above diagram. Within the X, each MAS can be written forwards or backwards.

Here's the same example from before, but this time all of the X-MASes have been kept instead:

.M.S......
..A..MSMS.
.M.S.MAA..
..A.ASMSM.
.M.S.M....
..........
S.S.S.S.S.
.A.A.A.A..
M.M.M.M.M.
..........
In this example, an X-MAS appears 9 times.

Flip the word search from the instructions back over to the word search side and try again. How many times does an X-MAS appear?
*/
------------------------------------------------------------------------------
-- Input data
------------------------------------------------------------------------------
    IF OBJECT_ID('tempdb..#rawdata','U') IS NOT NULL DROP TABLE #rawdata; --SELECT * FROM #rawdata
    CREATE TABLE #rawdata (ID int IDENTITY, Val nvarchar(4000) NULL);

    DECLARE @UseSampleData bit = 0;

    IF (@UseSampleData = 1)
    BEGIN;
        RAISERROR('Sample data',0,1) WITH NOWAIT;
        INSERT INTO #rawdata (Val) VALUES ('MMMSXXMASM'),('MSAMXMSMSA'),('AMXSXMAAMM'),('MSAMASMSMX'),('XMASAMXAMM'),('XXAMMXXAMA'),('SMSMSASXSS'),('SAXAMASAAA'),('MAMMMXMMMM'),('MXMXAXMASX');
    END;
    ELSE
    BEGIN;
        RAISERROR('Real data',0,1) WITH NOWAIT;
        INSERT INTO #rawdata (Val) VALUES ('XXXMMSAMXXMASXASAMMSMMSAAMXMAXSAXMSXMXSAXMMXXXXMXAXXXMASMMSSSSSMMMSMSMMSMSMSMMSXMXMMSMMMMAMXSMMMMSSXMASXSMAMSMAXMAMXSXAMSSMSSSMXSMSXXXXAXMMM'),('AMSMMASAMXXXXAXMAXAAMSAXXMXAMAMXAMMAMAMMSMSMXXASXSMMSMMSAMAAAMXMAMAAMMMSASXXMASAMXMMMAMXSAMMMAXMMAMAMASAMXASAMMMSAMXMMMAAAAAAAMASMXMSMSMMSAM'),('MAAAMAXXASMMASASMMSSSXAXMXSAMASMSMMSMAXAAAAAMSMMAMXAAAAXAMMMMMASASMSMMAMAMSXMASAMMXASAMXSASMSSMSMSXSMAMXMSXSASAXMAMAAAXMSSMMSMMASAMXSAAAASAS'),('XSMSMSSMXAAMAXMASMXMMMMSAMXXSMSAMXAMSSSSMSMSMAAMAMMXSXMMSMASASXSXSXMAMXXSAMXMASXXASMSASMSAMAXMAAXMAMMSMSXMXSXMASXXSXMXSAMXMAMAMXSASAMXMMMSXM'),('XXSXXAAXSSSMSSXMMMAXMASMMMMXMAMMMMXXAMAXAAAAMMMMASAAXASAXMASASXSASASXMAMAASMSAMAMXSMSAMXMAMMMMXMSMMMAMXMAMAMAMSSXMAMMSAMXAMMMAMASAMMSASAMXAA'),('XMASMMSMMAAAXXXMASXMMMMAAXXAMAMAXXMMAMMMSMSMSXXMSMMMSAMASMAMAMAMAMAMSMSSSMSXSAMXMASXXMAMXAMXAMAXXAXMAMMSAMAMAXAXAAAAMAMMSSXSXXMAMAMXMAXASMMM'),('SMAMXMAXXAMMMMMXAXAXSSSSSSSXSSSXSASXMMAAAAAAXMMXAXXAMXMSMMSSXMXMAMAMXMAAAAXASAMXMAMXMAAMXXXMAMMSSMMMMSASXSXSAMMXXMXSXAXMAMASAMSSSMMMXMMMMAXA'),('XMMSSSMSSMSAXAAMSSSMMAXAAAAAXAAASAMXASMSSSMMMAMSMMSAMXXAMAAXAMXSXSAAXSMXMMXMXAMXMMSMAMAMAASXXSAAXXMAMXMXXMAAXMMASMMMMXXMAMAMAMAASAAMASAMXSMM'),('MAXAXAAAXXSXXMXSAAAMMMMMMMMMMMMMMAMSMMMAAAAASXMAAASAMMSMMMSSMMAMMMMMXMMXSAMSSSMXMMAAASAMSMSAASMSSXSASMSSMMMAMSXXXAAMSSMSMMXSMMMMMSMSASXSAAAM'),('AAMXSMMMXMXMASXMMXMMSXMMXMAMAAXASAMAXAMMSMMMMASMSMSXMAMXAXMMMAXXAAASMSAXMASAAAMMXSASXXAXMAMMMMMAMXSASAAMXAMMASMSSMMSAAXAASMMMASMMAXMAMAMMSMM');
        INSERT INTO #rawdata (Val) VALUES ('SMSAXAXAMSAMSAAMAXMASASXMMXMSMSXSXSMSXSXMXXXMXMXAMMMMXMSASXASMSSSXSAAMSSXMMMSMMAXSAXXSMMMMMMXXXXXAMAMMASXXSMAMAAAMSMMSMMXSAASASAMSSMAMAMAXAM'),('MAMASAMXMSASXSXMASMASMMAMMAMAAXMSASXSMMMXMAMSMSXMAMAMSMSSMMXSAAAXXMMXMASAAMAMXMSMMASMMSASAAMSSSMAMMSMMAXAAXMAMMMXMXAXAAXASMMMMXAMMAMAMAMMSXM'),('MMMMMXMSMMXMAXXMAXAAMASXMSASAXSAMAMMXAMSSXSAAAXAXMSMMAMSAMAMMMMXMXXXXMASMMMAXMXMSMAMAAXXMSXSAAAXXMAAMMMMAMSMXXASASMSSSSMXSXMASXSMSAMXSASMSXS'),('MXAAAXMAMXSMMMMMMSMXSXMAXXAXASMAMAMAASAAXAXSMSSMMXAXSSXSAMXXAXSSSMMSAMAXXAMAXSAMAXSSMMSSMMMMMMMMXMXXSAMSAMXMASXSASAAXMAXAXASXSAAAMMSMMASAMXM'),('XSSMSSSMSMMAMXMAXAMMAASXMMSMMMMAMXASAMMMMAMAXXAAASAMXMASMMSMMMSAAAAMXMMMSXSXXSASMXMAXMAAAASMSAXAMMMASAMSAMAMMMMMMMMMMSMMSSMMAMXMMMMAASXMMMAS'),('AMAMAXXXAAXAMXXXXMSAMXMAAAXAXASMSXAMXXXXMAXXMMSMMSMSSMAMXAAAAMMXMMMSMXAAXMAXMXXMXMSASMSSSMSASAXSASAAMAMSAMAMAAAAMSMMAMAAAAXMXMSXAAXMMMAAMSAS'),('MSAMMMMSMSSMMSSSSMAXXASXMASXSMSAAXXXMAXSMSSSMMASXXAAMAMXMMSSMSASXSXAMSMMXAMXMMSXMAXASAMAXAMXMXAMMXMSSSMSASMSSSSSMSAMMXMMSSMMAMAMSMSMMSMMMSXM'),('XSXMAAAAAMXXSAAAASASMXMXMXMAAAMXMMXMAMXSAMAAXXAMMMMMSMSMMMMMMMMMAASAMAMXXSASAASAXMMMMMMAMXMSSMSMSMXXAMAMXMAAAXAXASAMMASXMXAXXSMXAMAXMAXMMMAM'),('XMAMSSXMSMMMAMMMMMMMXAMXAAMSMMMAXAXSSMAMAMXMMMSMSASAMAAAASASXMMMXMSXMSXSXXASMASMMXXXAAMXSSMMAAAAAAMMMMAMSMMMSMMMAXXMSAMASMSMASXSASAMSXMSASAM'),('MSSMMMMMAAAXMXSAMMSMSMAMSXXXAMSMSXMAMXASXMAXXXMASASAMSMSMSAMMXSAMXMMMMMMAMMMMAMMSAMMSMMAXAAMMXMSMXMMAMAAMAMXMXXSSMMMXMMAMAXMAMAXAMAXMMASASXS');
        INSERT INTO #rawdata (Val) VALUES ('MXMXSAAXSSMSMAXASAAMAMAMXMMXSMMXSXXSXSXSMSMSXMMMMXMXMXAAAMAMSASAMAMAAAAMAMAXMMSAXMAXAMMMSSMMAMMAXXASXSSMSAMAXAXMAASAAAXSMMXMMMMMXMXAAAXMAMAS'),('XASAMXMMMXMAMMXMMXXSMXAMAAMAXAAASAMXMMMSAASAASAMXAMASMSMSMMXMASMMASMSSSSMSMSMXMASMXSASMXAMXMMMMAMMXMXXAASAMASMSSXMMMXMSAAXXXXAAXXMMSMSAMXMSM'),('SMMMSAXAMMSAMSASXSMAMSMSMSMASAMXSMAAAXASMMXSXMAASXSASAAMXMXXMXMMSASAMXMMMMXSXAMAMXAMASXAMMSASASXSXMSMMMMMAMXAXMAMSMSMSMXMXMAMSMMASAAAXXMXMAM'),('AXAXXMXASAXXMSXXAAMMMAAAAMMMMAMXSXSSSMMSASXAMMMXSXMASXSXMMSMXSAMXAMMMAXMASAMMXASMMXMAMMMMASXMASAAMXAAAXXXSMSXMMAMAASXSAMXAMMXAMMAMSXMXAMXMAM'),('MSMSAAMXMAXMMSXMSMMXSXSSXSAMXAMMSAMXMAMSAMXMAASXXAMAMAMXSXMAAMMMMXMSSXSMAMAMAXAMASXMASMXMXXAMXMMMASXMMSSXMAAXMSMSMSMAMAMSSSSSMSASMXXMSAMXSAS'),('XAAMXMASMMAMXMAAAAMAXAAAXSASXSMXMXMAMMMMXMXXSMSMSSMASMMAMAMMMXASXSMXMXMMASMMSAASAMXSAMXAXMMMMAXXMMASAXAXAMSMMMAMAXXMXMAMAAXAXASAXAXXAAAXMMAS'),('SMXMAXMAAASMMSSMMXXAMSMMMSAMAXMXMSSMXSASXMMMXXSAMASAXXMXXAMAMXAXAXMAMAMMASMAAMMMMMAMASMSSMASMMMXXMASXMASMMMAXMAXMSSMXXMMMXMAMMMMMMMAMSMSSMAM'),('XSSXSSSMMMMAAAMMSAMSXXAXXMSMAMSMMAAMASMSAAAAMAMAXAMMSMSMSMSASMSMSMSASXXMXSAMSXMASMMSMMXAXMASASXSXMAMAAXAMASAMXXSXAAXSMMMSMMXAXAAAAAMMAAXAMSS'),('MXSAAAXXSXMXMASAXMAXAMXMSXMMMMMXMXMMMXMSXMMSSXXAMSSMAXAAAXMASAAAAASAMAASAMAXMMSAMXMMASMMSMMSAAAXXMAMMASMSASASXXAMSSMAAXAMAMMXSSSSSMSAMXSMMAX'),('XAMMMMMSAAASXMMXSXSMXMAAXASXMASMSSMXXMXSMMMAMAMSSMAMXSMSMSMMMMMSMXMMMSMMASXMAXSSSXXMASAXXAAMMMMMMMSXSASXMAMMMMXSAMXMSMMMSAMSMMMXMXASXSXMAMXM');
        INSERT INTO #rawdata (Val) VALUES ('MMMXXXXMMSMXASMXMAXAMXSMSAMASXSAAAXMXMXMASMAXAAXAMAMMMXAMXAAAXXMMXMXMAMMAAXSMMMAMMXMASMMSMMXSAMASXXAMXSAMSMSAMMAAAXMAXMAXXSXASMSSMXMASASXMAS'),('AASMMMSXMXXSMMMAMAMAMMAXXAMAMSMMSMMSMSMSAMMSSMMSAMXMAMSSSMMMSXMXSAXSAMXMMSMAAAMAMSASAMXMXAAAXASASMMXMAXXMAMSAMAMMMMSMSMMSMMMMMAAAXMXMSAMMSAA'),('XXAAAAXXMXMMMASMMMSSMAMSXMMMMXXAMXASMSAMXSAXXXMAMXXSXMAXSAMXMXMASMSMXXMASMAXMMMXMMAMXAAMMSMMSAMMMAXSMSSMMAMSXMMSAAAAMAMMAAMMMMMMMMMAAMAMAMSS'),('MSSXMSXXMAAASXSMAAMAMMXSMMAXXSMSSMMSAMSMAMASMMSMASXAMMSMSSMAMAMXXXXMAMMXMASMMSMSMMAMMSMSAMAXXAMXSSMSAMAMSMXXXAMMMMSSSSSSMSAAASXMAMXAMMAMXXAX'),('XAAMSAMSMMXASMXXMXSAAXXMAXMSXXAXSAAMXMAMXMXXAAXMASMMXAAAXAMSSXMSMSMXSMMXXAAMAAAAMXASAAAMASASMMMXMXAMSMAMMMSSMSMMSMXAAXAXAAMXMXASXMSASXAAMMSS'),('SMSMMASAASMMXXAXMAMXSMSMSAXAAMMMSMMSXMAXMMMSMSSXXXAXMSMSMXMMAMXAAAMMXAMXSSMMSMSMSSXSMMMMXMXXAASAMMAMXMSSXAAXMASAAAMMSMMMXMMSSSMMXAAAMXXMAAAM'),('XXAAMSMMAMAMAMMSSSXAAXAAMMAXXMMASAMXASXXSAAAMMMMAMSXXMAMXAXSMMSMMMSASAMAMAXAXXMAMAAMAXXSAMASMMMASXMXMAAMMMXSXMMSSXSAAAASMXMAAAXSMSMMMXMSMMXX'),('XSSMMMAXMSSMAXXAAXMAMXMXMXXMSXMAMMMSMMAASMXMMAAMAMXMSMMMSXXAXMXSAMMMSAMASXMMMSMSMSXSAMMAMMXAMXSXXAXAMMMSXSMXAXXXXMMMSSMSMAMMMMMMAAXAXXAAXMSS'),('XMASMSMMMAMXMSMMSMAAAASXXSAAMAMSMSASMMMMMSMASXSSMSAXXAXASMXMMAASXXAXXMSMSXAAAAAMXMXMASAAXSAMXMAMXMMXSAMXAMXSMMMAMSAAMAMXMSSMXSXMSMSSSMSSSXAA'),('MMAMXASXMAXAMAMAAXMMXXSAAXMASAMMAMASMSMMAXMAMMAAASMXSAMXXAMXXMXSASMXMXAAMXSMSMMXAMXAXXMASXSXXAAXMXSSMMSMAXAMAAXASMMMSASMMMXXMXAMXAAMAXAAMXMM');
        INSERT INTO #rawdata (Val) VALUES ('SMAMSMMXSASXSSMSXSXMSSMMMMXAXASMMMMMMAAMXSMASMMMMMMXMXASXSMSASMMAMAASXSSXAXXXXAMXMSXMSSMSAMSSSMAMAMAAAXMSMMSSMSXSAAXXASXSXAMMSMMMMMMSMMAMAXX'),('SMMXAAXMMASAAXMMASAMXAAXMASMSMMMXAXASXSMAXXAXXXMAMXAMXSMSAAXASAMXMSMMAAMMMMSAMSAMXSAAAAAMAMAMAMAMASMMMSXXAAAAAXXSMMSMSMAMMMSAAXAAAMXXXSASXSX'),('MAMXSMXAMAMMMMAMMSMMMXMASASMAXMASMSMXMAMMMMSSMMSAMSASMMSSMMMXMXXAAXXAMMMAMAAAXMASXSXMMSMSSMMSASMSAMAAXAMSMMSMMMXXMAMMAMAXMASMSSSSMSXMASAMMMM'),('MAMXMSXMAMXMMSMSXMMSAXXXMASASMSAMXAMAXAMSAMXAAXMMASAMASXXMASMMSSMSMSXXXXSMXMXMXMXXMASMMAAAAASAMAMXXMMMMAAMMXXMMMAMMXSASXMMXSAXXAMXSAMAMSMSAM'),('SASAAMMSMSMSAAXSAAAXMAXMXSXXMASAASMSMSMSSSSSMMXAMAMASXMMASASAAAXAAAASAMXMXSXSMSMMXSAMAXMSSMMMMMSXMMSAMXSMSMAMXAMASXASASXASAMMMXMMXSAMASAXSAS'),('SSSMSMAAAAAMSSXSAMMSXSXAXXXXMAMSMSAMAAXMXAMXAXSXMXSAMMASAMSSMMMMXMXMMXMAMMAAAAAAMAMASAMXAMXSXXAXAMAAAMMMXAMSMSXSASMXMAMMXMASAMSAMASAMXXMASAM'),('XMXAMMSMSMSMAMASXMAXAMMXMSMSMSMMMSMMXMSXXSMSSMMASAXMASXMASAXAMMSAMAXAAMAMAMSMXXMMASAMXXMASASXMSSXMMSSMASXMMMMMAMASAMMSMAMSSMAMXAMASAMXSXXMAS'),('MAMXMAMXMMMMXXAMXMXMXMAAMAASXMASAMXMSMMMMMAMXASXMASXMSAMXMMSXMASASMSSSSSSSXAXAXSSMMAXXXMAMXSAXAMAMMMAMASAXAAAMAMXMXMAAXXAXAMSMSSMXSAMSAMXSAM'),('XSXSMMSMSAAAXMSMMAAXAMMXSMMMAMAMAMMMAAAAAMMMSMMMMMMAASMMASXMAMMXXAAAXXAXAMXSMXMAAASMMAXMAMMMAMXSAXAMAMXSMSSSSMMSXSSMSMSASXXMMAAXXXXXMAXXAMXS'),('XXAMXMAASXMSSXMAMSMSSSMAXMASXMSSXMXMMMMXXSMMAAAMAAMMMMXMXSAMXMXXSMMMSMSMMMMAASMSMMAAMAMSSMMXSXMSMSMSXSAXXAMMXAAXAXMAAAAXXMASMMMXMSMSMSAXXMMA');
        INSERT INTO #rawdata (Val) VALUES ('XMSMAXMXMMSXMASMMAMMAAMSMXXMAAAMXSMSMXMSMXAAMXSSSSSXSXMXASMMAMXMMAAAXXXAAAAMSMAXAMSAMAXAAASAXAAXAXAAXMAMMMSAXMMMSMMMMMMSMSMSMSMSAAXAAMMSMSXA'),('SAMMSXSAAXMASAMXMAMMSAMMASXSMMMMMXAAAASAMSMMXAXMAAXXMASMAMMMMXAASXMSSSSSMSXXMMMMXAMAMMMSMMMAXMMMXMXMXMXXSXMXSSXXAAMASXMMAAAMAAAMXMMMMXXAAAMX'),('SASAXXSSXMMXMXXMSXSAMAXSAMXAASAAMMSMSMSAMMXAMSMMMMMSXAAMSMSASXMXMAAXAXAAXMASXXAMSXSSMXMMMSMMMAXAMXAXASAMXASAAAXSASXASASMSMSMMMSMAXXAASMMSMSA'),('SAMASMMMXSSSMMMMAXMAMAMMMXSMMMSMSAXMXASXMSMSXMASAMXSMSSXAASAXXXXSMMMXMSMMSMMASMXMMAAAMMMAAAASMMSASMXAXAMSMMMMMMSAMMXMAMMASAMXAAMSMMXMSAAAAMM'),('MAMAMAXXXAAAXAAMXXSAMAMASMSXSXAXMXSAMMMAMMAMAXMSASAXAMMMMXMAMSMXMASXMMMXAMXXMMMAASMMMMXMSMSMSAMAXAMMMMSAMXXAXSAMASMSMAMMMMSMMSMAAAMXMSMMMXMX'),('MXMXMAMSMMSMSSSMMASXSMMMSAMAXXXMXXMMMAMMMMAMMMXSXMMMXSAAMASMMSAAXXAXAXMMMMXMXAXSMMAAAXXMXXXXSMXSMMXAAAMXMXSMSMASMMAAXSXXAAXXXXMSSSMAAMMXXSXM'),('SASMMSMSAAXAAAMASAMXAAAXMMMSMMMMXMSXSSSSXSASMSAMXSMAAAMAXAXAAXSSSMMASMMXSASMSSMXASMMMMXSAAMXMXMXAMSSSMSASASMXXAMAMSMSMMSMSSMSXMAMXMMSXMSMMMA'),('SASAAMASMMMMMXSXMASASMMSAASAMMAMAXMAAXAMASAAXMASAMMMXMSSMSSMMXAMAAMMXMAAMASAAMAXAMXMAMMSMMMAXAASAMXAXASXMASAMMSSSMXSMAAAMMAAAXMASAMSMXMAAASM'),('MXMMXMAMASXXAXMAMXXAMAAMMMSASMSSMSMMMMAMAMXMASAMXSMMSMAAAXXASXSSXMMXXMMSSSMMMMSMMXAMAXAXAAXMSMMMXAMXMXMMMXMXMAMMXXMAXMXSMSMMMSXAXAXAAAMSXMXX'),('MASAXMASAMAMXXXAMXMSMMMMMXSXMAMAXAXMAAXMXSXMMMMSAMAASMSMMMSMMAMMASMMMSAAXAASXAXMAMMMMMMMMMXXAMAXASXSMXMAMASMSMXXXMSSMSAXAMSAAXMMSSSMSMXMMSSS');
        INSERT INTO #rawdata (Val) VALUES ('SASAMXAMMSAMSSMSSSMASAAXXAMAXSSMMMMSASMSAMAXMAXMAMMMSAAAAAXXMXMSAMAAAMAMXSMMMAMSAMXASASXAXMASMXSAMAASXSMSAMAAMXMSAAAAMASASMMMXMMAAAAMXAAMXAA'),('MAMMXMASMSAXXAXXAMXAXMMMSSMMMAAMMXASMMXMASMMSSMXAMSAMXMMSMMXMXMMMSSSMXSSMMSSXMASAXSAMAXMXXMXMAXMAMSMMXAAMAMSMMAAAMMMSMXMMMAAMSSMMXMMMXMXMMSM'),('SSMSXSASASMMSSMMAMMMSAAAAAMXXMAXMMMXAXSSMMAAAMMSMSMSSSMXXAMSSSMAMAMAXAMAXAXSAMXSAMMSMSMSSSSSMMMMAMXAXMMMMAMXASMSSSSXMXMMMSSMSAXAXASXSMSAAMAS'),('SAAXAMAMAXMAXAMSSMAXSXMXXSASMXSMAMASMMXAASMMMSAAXSXXMASAXAMXAASMMASAMXSMMMSSXMAMXMAXSAASAAAXAXASASXMMMXAXMMSAXAAAXMASMMAAAAMMMSMMMAAAAMMMMAS'),('SMMSXMAMSMMSSMMAASMMMASXMAMAAAXSAMXAXMSSMMXXSMMSXMAAAAMMSSSMSMMMMMMXSAXXAXAMAMXSMMXSXMXMMMMSXSASXSXSASXMASASXMMMSMSAMASMSSMMAXAAAXMMMMMXSMSM'),('XSAMXMXSXAAAAXMSMMXASAMAAMXMMAMMXMAMXXAAASAMXAMMXSAMMSSXAAMMASASMMAMMMSSSMXXAMXXAXMAMXXMXMAAMMAMASASASAMXMMMXMXAAXMASAMXXAXSAMXSSSXSXXMAMXAX'),('MMMMXMXMXMXMMMMXXMMMMAXAMXSXSSSSXSAXSMSSMMMASMMMAXASXAAMMSMSAXMSAMXSAAXAMAMSMXMASMMSXMXXAXMSXMAMAMMMXMMSXMXSAMMSMSAASASMMMXMXXMXXMAXAMMMSSSS'),('XMASAMXXAMSMSSXSASAASMSSMMSAMAAAASXMXXMAXXMMMSAMXXSMMMSXAMXMMSMSXMAMMXXMMAMAASXMXAAMAMASMSXMASAXAMXMASMAAMAXASMAMXMASAMAAAMMMMMMAMAMSMMSAXAM'),('MXAAAAXMMAAAAMAXAMXMXXAASAMXMMMMMMMSMMAMSSXAASMSAXMAAXXMASAMXAASXMASXSMXSASXMXAXSMMMAMAAXSAXMMMXAXXMASMSSMASMMMASMSAMXMSMMSMAAAXAMXXMASMMMMX'),('AMASAMXAXMMXMXAMSMSXMMMMMMMXSXMXXSAMASXMAXSMMMAMMAXSMAAXXSASMMXMASAXAAXASASXXXMMSAMSXSSMMMAMSAMSAMXMAXXAMXAXMASXXAXXAAMASXAXSSMSMXSAMXMAAXXM');
        INSERT INTO #rawdata (Val) VALUES ('XAXXXAXSSSSMMMSSMAAASAMXMSAXMASXMMXSAMXMSMMXSMAMXMAAXXMAXMMMASXMMMSMSMMMSXXMMXSAXAMAXMAASMSMSAMAAAAMASMMXMAMSMMASXSAMXMAXXMMMAMSXAAAXAXSMSMA'),('MSAMMXMMAMXAAAXAMAMMMXSAAXMASMMASAAMMMSAXAMAXMXXAXSXMMXMMASMSMAXSAMXXAAAXMMXMAMAMSMMMMSMMAXMXXMMSSSMMSASXSSMXAXXAASASMMSSXSAMXASMMMSMSXXMSMS'),('XMASAASMMSSSMMSAMXXAXASMSMXXXASMMMMXASMMSMMMMASXSXMASMAMMMMMAMSMMASASXMSSXMAMAMXMXASMMMMMMMXXSAMMXMAXSAMAAAAMSASMMSAMMAAAMSXMSSXAAXXAXASASAA'),('XSAMXMSAAXMASAXASMMSAMXAXAMXSMMASXSSMSAXXMAMMAMAXMXXMSASASAAAAXASXMMSASAXASXSAXSASAMMAAXAASMMMASMMXXMMAMMMMSMMAXXAMXMMMMMMXXASASXMSMAMAMAMSM'),('XMSSMXSMMSXAMSSXMAAXMXMMMMAXMASAMXMAMSXMXMASMSMSMSMMMXXSASAXXSMXMAAXMMMASMMMSMSAMMSMSSSXSMXAXSAMMASXMSXSAMXXAMXMMAXMSASASMXMMSAMXXXMAMAMXMAX'),('SXAXMASAMXMMSAXMMMMMAAXAAXMMMMMAMXSAMSASXMAMXAAAAAXSXSMMMMXMSXXASMMMXXMAMXSXSSMAXAXMXAAMMASXMMASMAMAAAAXXAMMMMMXSXSAAASAAMAMXMAMXMSSMMAXAMAX'),('SMMSMMSAMAASMXSMSAAXSSMSSXSAASMSMAXXSMMAMAMSSMMMSMMASMASMAAMMASMSXMMMXMMMAMMMAMSMMXXMMMMXAMMASAMMSSMMMSMSMSASMSMMMAMXAMXSSXSASAMAMAAXSMSSMSS'),('XAXAXXMXMAMSAMSASMMMAMAMAMXXAXAMMMMMMXXXXXXAXAAMAMXMASAMMXXAMXMXSMSAAXSAMASASMMMASAASXSSMSMXXMASAMMXAXAAAASAXMAAASMMMXXXMAASASASXMXSMAAAAAAX'),('SSMMMXMAXMMMAMMMMSXXAAMMAMXMSMMXASAMXSXMMAMMSMMSAMAXAMXSASXSXMAXXASAMXMXSASMSXXSAMSSMASMAMXMASXMASXSAXMMMMMAMSMSMSXXMAMXMMMMXMAMMMSXXMASMMMS'),('XMASMASAMXASXMXSMMXSMMXSXMXAAAXSMMAXAMMXMAXMAAMSASXSMMMSASAXAMXSMAMMSAMXMASAXAMSXMXMMMMMAMAXXMAXAMMMSXASMMSSMAAMXMMMSAMMXMXMAMXMXMAXAMXAMXXX');
        INSERT INTO #rawdata (Val) VALUES ('XSAMSMMAXXAXAXAAAAAXASAMMMXXXXMAMMSMAXAAXMMSXSMSAMAAAXAMXMAMXMAXAMAASAMMMSMAMMMMXXXXASAMMSSMXMMMMXSAAMAMXAAMMSSMASAXSAMAAAASASASXMMSAMMSMMMX'),('MMMXASMASMSMAMSSMMXSAMMMXSAMXXSASAMSSSSMSAASAXMMSMXSMMMSMMAMAMAMMMMMXMMSSMXSAMAASMMSMMASAAAMXXSAMAMSSSXMMMMXAAAMXMSXSAMSXSMSAMAMAAXMXMAXMASM'),('SAMXAXMASAMMSMXAAAXMXMAMAMASAASAMMMAMXAMXMAMAXXAAXAMXXXAASXSMSASMAXXSMMMAMAMASMXSAASMSMMMSSMMAMAMXXAMXAXMSSMMSSMXXMMMAMXMMMMMSMSAMXSAMXXXAXA'),('SASAMXMXMAMAAMXMMMXXAXAMASASMAMXSAMXMMSMXSSMSMMSSSMMASXXXXAMXSASXMAMAAASAMXMAMXSSMMMAAXMMAAMAAXAMXMASXSSMAMXAMXXXSAAXAMXAXXAAMXAAXMMMSMSMMSM'),('SXMAXXAXMMMSSMASASMSMMSXMMASXXMAXXMSAXAAXAAAXSAMXAAAXSASXMMMAMMMMMSSSSMSXSSMSSMMXSAXXMASMSSMSMSMMMSMMAAAMASXMAAXMXMSSSSMSASMSSXMMMAAMAAAAAAX'),('XMSSXXSMMSAAAXMSAXAAMAXAMMMMMAMXSAXAASMSMMMMMMMMSSMSAMAMMAXMASAAAAAMXXAXAAAAAXMMASXSXAAMAAMXXXAAAMASXMMMMASAXMMSMSAMAAAAXXMAMXMXSXSSSMXMSSMS'),('SXAAMXMAAMMSMMMMXMSMMASAMASASXSMMXMMXAMAAAAAAXAAMAMAAMSSSSMAMXMSSMSSSMMMSMMMMMSMAXASAMXMMMSMXMMXMSASMSAXMASXMASAAXAMMSMMMSSSMMAMXAMAAAXXAMXX'),('AMAXMAMMMSXXASXXMAAXMASXMASASAAXXAAXMMSMSMMXMXMSSMMSXMAAXMAASXMXMAMXAMXAXXXXXAMMSMXMXSAAAAAASMSSXMAMASMSMMMMAMMMSMXSAXASAAMAAXSMMSMSMMMMAXXX'),('MMAMSASMMMASAMXMASXSMMXAMAMXMMMMMMSSMMAXXMXSMSMAXAAXAMMXMXSMMAXXMXMSMMXSXMMMMSAAXAMMSSMSMSSXXAMAXMAMXMXAMAAMSXAAAXMMASAMMSSSMMMAAXAAXSXSSMSM'),('XMAMMASAAMMMMMSAXMXMAMSMMSSMASXAAAAAAXMXMSXSAAMASMXSXMMXXAXMSMMMSAMAXSMMMSAAAXMASAAXXXMAMXMAMSMMXSASMMMMSSSSMXMSSXXMXMMMAAAAMASMMMMMSXAAAAAM');
        INSERT INTO #rawdata (Val) VALUES ('XSMSMXSMMXSAXAXSMMMSAMAAAXAMASMSMSSSMMSMAAAMAMMMXMASMAXMMSSMASXAMASMMMAAAXMMMXMASXMMMMSMSAMXMMAXXMXSXMXXAXMAMAMAXMXSSSXMMXMMMXMXXASMXMMMMSMX'),('MSAXMAXASASXMMSAMAAXASMSMSXMASAMAXAMXAAMSMSAAMAXASASMMMXAAAMAMMMSAMXASXMMSXSMXMAMXXAAAXXMXSSMSMMMMMSAMAMMSSSMMMASXXMAMMMSAMSXSMMSASMSASXMAMM'),('AMMMMASXMAMXSXSXSMSSXMAAMMAMAMAMMMSMMSSMXAMXSSXSASAMAMSMMSSMXSAMAMASXMASMSAAAXMASMSMSMMMMMMMAAMAXAASXMASXAXAAXMAMXMMAMAAMAXSAMSAAAXAXASXSASX'),('SAXXMMMMMSMMMAMAXAXMMMMMASAMAMSSXAXXXAXMAXSAMXAMMMMMAMAAMXXMXAMSASXMASAMAMSMMSSXSAMAMXMAAAASXMSSMMXSAMXSMXSSMMMASAXSASMSSSMMAMMSSSMMMSMAMASX'),('XXMSMAAXAXAAMAMXMAMMSAMXMSSSXSAAMMSMMMSMMMMAMMXMMAMSSSSSMMSXMMMSAMMSAMMMSMXMAXASMAMAMSMSXSMSAXAXSMAXMAMMMMMAMSSMSXXMMMAXAMXMMMAMXMAXSAMSMAMX'),('MAMASXXMSSSMSMSAMXXMAMXAXXMMXMXMAAAMAAAAAXSXMXXXMXMAAMMMXAMASXXMXMAMXXXAMASAMXMMSXMSASMXXXXMXMAXMMXSXSAMXAXAMXAXSXSASMMMAMSSMMASXSXMMAMAMXSX'),('MASASMSMMAMXXAXAMXXXMSMMMSAMXXMSMXSMMSSSMMSASAMSASMSMXAMMMSAMAXMMMMMSXMASMMAXAXAMXMMXXAMASMSMSSSSMAMAXMAMSMSXSAMXASAMSXMXMAAXSXSAAMSSSMMXASX'),('SMXXMXAMXMAXMSMSSMMMMAAAAXASMSMAXXMAXAXAXAMASMASMAAAMXMMMXMASMMSAXAASAXASAMXMMMMXAXSSMSMAMAAASMAAMXSASXSXMAMAXAAMMMAMAXSXSMSMMASMXMMAMSXMMMS'),('XXXMSSMSMSSSMXXMAXAASMSMSMXMAXXAXMMXMASXMMMAMXXMXMSMSASAAMAAMXAXMSMSSXMXSAMMASAASXSAAAXMAMSXSMMSMMAMASAMXMSMMSMMMXASMMASAMMMAXAXMAXMAMMMXAAS'),('SXSAAAAXMAMAXXMSMASMSMMAXMMMSMSSXSAASAMASXMMXSAXAXMASASXSAMMSMXXXAMAMMSASXMASXXXAMXMMMXMMMMMXXAXASAMMMXMSMXAXAASMMXXAXAMAMSSMMSXSXXMASXSSMSS');
        INSERT INTO #rawdata (Val) VALUES ('SASMXMMMMMSSMSMAXMMXMAMAMASXXAMAAMSMMASMMAMMAXMSSSMXMAMAXXXSAMMSSXSAAAMASMMMAMMSAMXXAMXMMAMMMMMSMMAXMAXSAMMMMSSMAMASMMMSMMAAXAMMSAAMASMAASAM'),('MMMSAASAMXAAAXSASXMASXMMSAMXMMMMMMXMSAMXXAMMMXXAMXXAMASMMSMSASAMMASXXAMXMASMAMASXMXMAXAAMASMAMMAMMXMMAMAMMXSAMAMMMXMAMAAXMSMMXSAXSSMASMSXMSS'),('MXAXSAMXSMSSSXXMXAMASMAAMAMXAXAXAMAMMXSASMSSSSMSXSAMSAMAMSAMAMMSMAMXSAMXSAMMAMXSASASXMSXSASXSMMASXSMMSSMXAAMMXAMXMMMXMSSXMAAASMMMAMXAXAXAMXM'),('MMSMXMAXXAMMXMAXSAMXSXMMMAXSSSMSMSASMAMXSAAXAAAMASXMMMSAMMAMSMMSMMXAAMSXMASMSSMSAMMSAAAAMAMMMMSASAAMAMXXMMXXSMSSSMAAAAMAMSSMMSAMMAMXAMXMAXAS'),('SXMAMMSSMAMAXSAMXSAMXAMSMMMMAAMAAXXXMASMMMMMSMMMAMAXAMMXXMXMAAXSASMXSAAXXXMAXAXMAMAMMMMXMAAAAXMAMXMMSSSMSSSMSXAAMXAMASMXMAXAAMMMMXSSMAMSMSAS'),('AAMSMAAAMXMAMMMSSXMMXMASASAMSMMMSMSMMAXXAAMXAMSMMSAMXSSSSMSSSXMSAMAMAMMXXXMASMMSXMSXSASXSXMMXXMAMXSXMAAXAAAAXMMSMSMSAMXSMXXMMSXMMAMAMSAAMMXM'),('MSMAMMSSMXMASAXMAMXXAXMSAAMMMMMMMASAMSSSSMSXSXXAAXXAAXAAAAAMMAXMMMAMXMXMAXMASMAMXAASAAAXMMSSSMSMXAAAXXXMMSMMMAXXAAMMXMAAXMASAXAMMSSXMMMXMMAX'),('MXXMMMXMAXXMSMSMXMXSASMMMXXAMASAMMMAMAAXAASAXASMMSMMMMMSMMXAXXMXXXXMAXAAMXMAXMAMXMMSXMMSXMAAAAXMMSSMMMMAXXAXXSMMMMSSMMSMAMXMASXMAXMMXSXMASXS'),('SMMSMMMXMMSMMAAAASASXSXAXMMXXAMASMSMMMSMMMMASASAAXAAAAXXXMSXSAMXSXASMXMSMMMSSSMSMAXMXMXXAMMXMMMXAMAAAAASMXMXMAXAMXMXAAAMAAXAAMAMSSMASAASXMAS'),('SAAAAAAMXMAAMSMSMMAMASXXSASXMSSMMXAAAAAXAAMXMASMMSSMMXXAAXAASASAMSMMSAAAAXAMAAAMAXAMAXSSMMSXSSSMSSSMSMSAMASAMMSSSMMSMMSSSSSMXSXMAXAXXSMMSMAM');
        INSERT INTO #rawdata (Val) VALUES ('SMMSSMXXASXSMAXXXMSMSMAMSXMAXAAXMSSSMSSSMMMAMMMAAAASMMXSMSMXSAMXMAXAXMSSXMXMSMMSSXMSMSMXMXMAXAAAMAXAXMXAMXMAMMAAAMMAXXXMAAXMMMMSMMSXMMXAXMAS'),('XAAXMMXMMMAAXAMXAAAXAMSMSASMMSAMXAAMMMAAXSSSSSSMMSXMMSAAAXXXMXMXMSMMSXXMASAMXXAXXMMAMXMAXAMSMXMSMMMMMMSXMASMMMMMMMSMSMXMMMMAMAAAXAMAMXMMMXSS'),('SMMSMAAXXMSMMMMMMMMSSMXXSXMXMMMSMMSMAMMMMMAMAAMMXXXAAMXMMMMXMAMAXAAXSAXSAMAXMMMSMXSAMSSXSASAMXXAAXAXAXMASMSXMAMMMXAAAAMXMASASMSSMMSSMXMXSMXS'),('XMAXMSXSAXXXMMMAAAXXMASAMSMAMMASXAXXXSSMAMXMMMMSAMMMMMMXMASASAXXXMSMXAXMASXMXAMXAAXAMAAASXSAMXMSSSXSAMMXSAMAMAMSSSMSMSAASMSXSXMAAXAMXXSAMXAX'),('SXSXAAMMXMXASASMSMSAMXMAMAMAXMAXXAMXXXAXXMASXXAMASXSAMXAMMMAMMMSXSAMMXMSAMMASMXMSMXMMMSMMAMXMAAXMMXMXSSMMASAMASXAAAMXXMAMXMAXAMSMMASXXMMMMXS'),('MAMMMMSSMXSAMASXAASMMSXMMMXSXMXSAMASMSMMMSMSMSSSMMXSMSSSSMMSMMASMSASMAMMSSMXMSAXAMASAMMAAXMSSSSMMSAMSAAASAMXSXSMMMAMMXXXMASAXSMMAMXXMASAASMA'),('MAMMMAXAAXMXMAMMMMMSMAASXMAXASAMXSXMAAXAXAAXAAXMAMXMMXXMAXAAAMAXASAAXAXXAXXXAMMSXSASASXMXASXAAXAASASMSSMMMSAMAXAXXMXSAAMMMSXAMXMAXAAAMMMMXAM'),('MSSXAMSMMMMAMAMAXAAAMSMMAMASXMAMXSAMSMSSSMSMMMMXAMXXXMASXMSSSMMSXMXMSSSMMSSMAMXMAMASMMAMSMAMMMMSMMMMXAMMAAXASMSMMMMAMSSMAXXMAMAMAXSXMXASMSSX'),('XAMMSAMXAAMASMSMMMSXMAXSSMAMMSMMAMMMXAXAMXMASMSSSXSAMMMAAAAXXMXMMAAXXXAXXAAXSMMMMMAMASXMASAAASAMXSMSMSSSMSSMMAAXAAMAMAXMXMAMMSAMAAMAMSMSAAXA'),('MSSMMAXMXXSASAAXXAAMXMAMMXAMAAAMAXSAMXSMSASXMAAAAAXMMAXMMMMSXMASXSMSASAMXSMMXMAXAMMSMXMXAMMSMXAMASAAMXMXXXXMMSMSXSSXMASXMXMMMAXMMXSAMAAXMMXA');
        INSERT INTO #rawdata (Val) VALUES ('AXAASAMMAAMAMMMXMASMSSXSASMMSSXSAXMMSXMASASAMMMSMSSXSAMSXSAMXMAXAAAXMMMSMMXXXASMMXMAMMSMSSMAXMAMAMSMSXMMSMSMAXXXAXXXMAMAXASASAMXSASMSMSMXXSS'),('SSMMMAXMMSSMXXSSMMMMXAAXAAAAMAMXMSMMSXMAMXMAXMXMXMMAXAXSAMMSMXSMSMMSMAXAASMSSMMASMSMXASXMAXAMXAMXXAMAAXAAAXMAXSMSMASMAMSMMSAMAXXMASAAMAXSAXA'),('MAXMMSMXMMAMSXMAAXXSMMMMSMSXSXSMAAAXSAMMXSMMMMAAAMMSMSMMAMASMAMMMAAXXASMXMAASXSAMAASMXSAXAMSSSSSMMAASMMSSXSASXSAMXXMSSXMAMMMMMMMMAMXMSASMAMX'),('AXMXMAXXMMAMSASXMMAXAASXMAMMMMSASMSMSAMAAMASASXSMMAAAAAXXMASMXMAXMXMMMMXSMMMSXMAMXAMMMMXMSSXAMXAASXMAXAMAASAMXMSMSMMXMASXMAAMASXMAMAXMXMMAAX'),('SMSAXXSMSSSMSAMXMXMMXMSAMMMMXAMXMAAASXMMMSASAMMAASXMSMXSAMASXSAMXSXMASXMXXAXMASMSMSMSSSSXMXMMMSSMMMSMMXSMXMAMSMMMXAXAMAMXMMXMASXXXMSMMMMXMXM'),('XAXXXSAAAAMAMMMMSAMXSAXXMAAMMSMSMXMMMXAAMMMMMMMMMXMAXAAXXMMSMSAMMSAXAMAMMSSMXXMAXAXAAASAMXXMXAXMMSXAXMASMMMAMAAMMMSXSMMXMSMSMASMSAAAAASMMXAA'),('MAMSXMAMMMMAMAAASASAAAXSSSMSAXMSAMXMXMMSSMXMAMXXAMMMMMMSMSXSXSXMASAMSSXMAXAXSSXAMSMMMSMMXMASASXMASXXMAMXAXSASXSMAAMXMAMXASAAMXMASMSMSMSAASXS'),('MAMAAAASMXSSSSMXMMMMMMMMAAAMASAXXXXAAXXAMXAASMXSASMXSAMXXMASAMSMXMASAAAMXMMMAAMSXMAXMAMXMAXMAXXMASMMSSXSSMSAMXAMXMMASAMXSMSMSAMMMAXAMAMMMMAA'),('SXMXXMXMAAMAAMXASMASXAXMMMMMAMMMMMSSSSMAMXXXXAAXMMMAMAXMSMAMAMXMASMMXSXMAMAMAXAAASXMSASAXXXMAMAMMSMAAAMAMXMAMSSMSSXASAMMMAMMSASXSXMXMAMAAMXM'),('AMSXSAMXMMMMMMMAASAXMXMXAAAMMXXAAMAAAXXXSSSXSAMXSAMMSSMMAMASAMXMAAAAAXAMASXSXSSMMMSASASXMMXMMSMSSXMMXSMAMAMAMXAAAXMAXAMAMAMXMAMAMAMXMSXMMXSX');
        INSERT INTO #rawdata (Val) VALUES ('MAXMASMXAAXASXXAMMMSMAXXXSAMXSSSSSSSMSSXMAAXSAAXSAXXAMASMXMSXXXMSSMMSXMMASAAAXAASAMMMMMAMSAMXAMXAMASMXXAXMMMMMMMMSASXMMSXMXAMAMXSAMXXMMXSAMX'),('XSSMAMXXAMXMMMMMXAXAMMXSMMXSAMXAXAMXXXMAMXMXSAMMSSMMASXMSAMXMMMXMAMSMASMMMXMXMMMMAMXAAMMAMASMSSMXMAXMAXSMSAAAMAXXXMXAMAAAMSSSMSMSXSXASAAMMSM'),('XMAAASXSMSAAASXSSSSSXSASAAAMXSMSMMMXMASMMASXMXMXMAMSAMXASMSAXSAMXMSXMAMAXAAXAMXMSMMSSSSXSSMMAAMMAMXXMSMXASMSMXSAMXASMMSSMMAAAXAAXASMMMMMSAAM'),('MSAMMSASASXSMSAAAAMXAMASMMMXSAMXAMXAMMMAXASAMMMASMMMXSMXMXXMMMXSXMMAMMXSMSMMMXAXAAMMAAXXMAMMMMMSMMMSAXAMXMAMAMXAXAXASXMAXXXSXMMSMXMAXSXMMXSS'),('AXASAXMMAMAMAMMMMSMMXMXMASAXMXMXAMSXXAXAMXSMMASASXAAMSMMXSMMAMXMASMSMAAMXMXMSSMMSSMMMMXSAMXSXMAMAAXMAMXMMMXMAMXMASAMAXSAMXMMMSXAXMSXMAMAMXXM'),('SXSMMSAMXMMXXMMXAMXMXMASMMMSMAXMAMAMSSMSAMXXSXSASXXSAXAMAXMSXXASMMAAMMMMASMXMAXAMXXXAXMAMSXMAMMXMMSSSMSSSMSXSMAMAMAXMXMAXXAAXMSMSAMSMXMSAMXX'),('XMXAAMMASMMSMSSMMMAXAMAMAAXAMAMMAMAXAMXAXAMAMXMAMXMAXXAMAXMAAMMSSMXAMXXSAXAAMAMSAMXSXXASMSASMMSAAMAXMXAMAAMAMXXMAXXMXXMXMSSMMMXMXXMAXMAMMSMS'),('MASMMXSASAAAAAXAMSMSMSSSSMSXMASASMMSAMXMMXSAAAMMMAAMSSXMSSMMSAAMXMMMSAXMAMSMSSMXASAMXMSMAMAMAASMSMASXMMSMMMAMXMSSSXMAMMAMXAMXSAMSSSMSMMXAAAA'),('AMAAAAMASMMMMMSAMAAAAAAMAAMXXSXAMAXSXMMXAASMMMMASXSAAAAMAAXAAMAMASAAMMSMAMXAMXASAMMSAXAMMMSSMMMAMAAMAAAAASMXSXAAAAMXAXSAMSXMASASAAAXSAAMSMSM'),('SXSAMSMAMXXXMXXMSMSMMMSMMXMASAXXSXMMMAXXMMSAMXMAXSAMXSSMSSMSSMMSASMSMMMMASMAMMMMAMXSXSASAXXAMXMXMMSSSMMSSMAASMMMSMAMXMSAXXSMMSXMMSMMXMAXMAMX');
    END;
------------------------------------------------------------------------------

------------------------------------------------------------------------------
-- Data prep
------------------------------------------------------------------------------
IF OBJECT_ID('tempdb..#letters','U') IS NOT NULL DROP TABLE #letters; --SELECT * FROM #letters
SELECT [Row] = r.ID, Col = x.Col, x.Letter
INTO #letters
FROM #rawdata r
    CROSS APPLY (
        SELECT Col = x.[value], Letter = SUBSTRING(r.Val, x.[value], 1)
        FROM GENERATE_SERIES(1, LEN(r.Val)) x
    ) x;
------------------------------------------------------------------------------

------------------------------------------------------------------------------
-- Part 1
------------------------------------------------------------------------------
WITH cte AS (
    SELECT x = STRING_AGG(l.Letter, '') WITHIN GROUP (ORDER BY l.[Row], l.Col) FROM #letters l GROUP BY l.[Row]
    UNION ALL
    SELECT x = STRING_AGG(l.Letter, '') WITHIN GROUP (ORDER BY l.[Row], l.Col) FROM #letters l GROUP BY l.Col
    UNION ALL
    SELECT x = STRING_AGG(l.Letter, '') WITHIN GROUP (ORDER BY l.[Row], l.Col) FROM #letters l GROUP BY l.[Row] - l.Col
    UNION ALL
    SELECT x = STRING_AGG(l.Letter, '') WITHIN GROUP (ORDER BY l.[Row], l.Col) FROM #letters l GROUP BY l.[Row] + l.Col
), cte2 AS (
    SELECT x = cte.x FROM cte
    UNION ALL
    SELECT x = REVERSE(cte.x) FROM cte
)
SELECT Answer = SUM((LEN(x.x) - LEN(REPLACE(x.x, 'XMAS', ''))) / 4)
FROM cte2 x;
------------------------------------------------------------------------------

------------------------------------------------------------------------------
-- Part 2
------------------------------------------------------------------------------
SELECT Answer = COUNT(*)
FROM #letters l
    CROSS APPLY (SELECT * FROM #letters x WHERE x.[Row] = l.[Row]-1 AND x.Col = l.Col-1) tl
    CROSS APPLY (SELECT * FROM #letters x WHERE x.[Row] = l.[Row]+1 AND x.Col = l.Col+1) br
    CROSS APPLY (SELECT * FROM #letters x WHERE x.[Row] = l.[Row]-1 AND x.Col = l.Col+1) tr
    CROSS APPLY (SELECT * FROM #letters x WHERE x.[Row] = l.[Row]+1 AND x.Col = l.Col-1) bl
WHERE l.Letter = 'A'
    AND CONCAT(tl.Letter, l.Letter, br.Letter) IN ('MAS', 'SAM')
    AND CONCAT(tr.Letter, l.Letter, bl.Letter) IN ('MAS', 'SAM');
------------------------------------------------------------------------------

------------------------------------------------------------------------------
